[package]
name = "wowitsaraytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
image = "0.24.3"
minifb = "0.23.0"
rand = "0.8.5"
rayon = "1.5.3"

[profile.release]
lto = true
codegen-units = 1
